import re

with open(r"C:\Users\Admin\source\repos\GestionPromocionesInmobiliarias\InmobilariaTopicos\InmobilariaTopicos\Form1.Designer.cs", "r", encoding="utf-8") as f:
    content = f.read()

expanded = """            // card1
            this.card1.BorderRadius = 16;
            this.card1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(26)))), ((int)(((byte)(43)))));
            this.card1.Location = new System.Drawing.Point(30, 280);
            this.card1.Size = new System.Drawing.Size(260, 110);
            this.card1.Controls.Add(this.c1S);
            this.card1.Controls.Add(this.c1V);
            this.card1.Controls.Add(this.c1T);
            this.c1T.AutoSize = true;
            this.c1T.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.c1T.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.c1T.Location = new System.Drawing.Point(20, 20);
            this.c1T.Text = "Promociones activas";
            this.c1T.BackColor = System.Drawing.Color.Transparent;
            this.c1V.AutoSize = true;
            this.c1V.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
            this.c1V.ForeColor = System.Drawing.Color.White;
            this.c1V.Location = new System.Drawing.Point(15, 38);
            this.c1V.Text = "18";
            this.c1V.BackColor = System.Drawing.Color.Transparent;
            this.c1S.AutoSize = true;
            this.c1S.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.c1S.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(211)))), ((int)(((byte)(153)))));
            this.c1S.Location = new System.Drawing.Point(20, 80);
            this.c1S.Text = "+3 este mes";
            this.c1S.BackColor = System.Drawing.Color.Transparent;
            // card2
            this.card2.BorderRadius = 16;
            this.card2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(26)))), ((int)(((byte)(43)))));
            this.card2.Location = new System.Drawing.Point(310, 280);
            this.card2.Size = new System.Drawing.Size(260, 110);
            this.card2.Controls.Add(this.c2S);
            this.card2.Controls.Add(this.c2V);
            this.card2.Controls.Add(this.c2T);
            this.c2T.AutoSize = true;
            this.c2T.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.c2T.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.c2T.Location = new System.Drawing.Point(20, 20);
            this.c2T.Text = "Viviendas registradas";
            this.c2T.BackColor = System.Drawing.Color.Transparent;
            this.c2V.AutoSize = true;
            this.c2V.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
            this.c2V.ForeColor = System.Drawing.Color.White;
            this.c2V.Location = new System.Drawing.Point(15, 38);
            this.c2V.Text = "146";
            this.c2V.BackColor = System.Drawing.Color.Transparent;
            this.c2S.AutoSize = true;
            this.c2S.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.c2S.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.c2S.Location = new System.Drawing.Point(20, 80);
            this.c2S.Text = "92 disponibles";
            this.c2S.BackColor = System.Drawing.Color.Transparent;
            // card3
            this.card3.BorderRadius = 16;
            this.card3.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(26)))), ((int)(((byte)(43)))));
            this.card3.Location = new System.Drawing.Point(590, 280);
            this.card3.Size = new System.Drawing.Size(260, 110);
            this.card3.Controls.Add(this.c3S);
            this.card3.Controls.Add(this.c3V);
            this.card3.Controls.Add(this.c3T);
            this.c3T.AutoSize = true;
            this.c3T.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.c3T.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.c3T.Location = new System.Drawing.Point(20, 20);
            this.c3T.Text = "Empresas asociadas";
            this.c3T.BackColor = System.Drawing.Color.Transparent;
            this.c3V.AutoSize = true;
            this.c3V.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
            this.c3V.ForeColor = System.Drawing.Color.White;
            this.c3V.Location = new System.Drawing.Point(15, 38);
            this.c3V.Text = "27";
            this.c3V.BackColor = System.Drawing.Color.Transparent;
            this.c3S.AutoSize = true;
            this.c3S.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.c3S.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.c3S.Location = new System.Drawing.Point(20, 80);
            this.c3S.Text = "Construcción, publicidad y venta";
            this.c3S.BackColor = System.Drawing.Color.Transparent;
            // card4
            this.card4.BorderRadius = 16;
            this.card4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(26)))), ((int)(((byte)(43)))));
            this.card4.Location = new System.Drawing.Point(870, 280);
            this.card4.Size = new System.Drawing.Size(260, 110);
            this.card4.Controls.Add(this.c4S);
            this.card4.Controls.Add(this.c4V);
            this.card4.Controls.Add(this.c4T);
            this.c4T.AutoSize = true;
            this.c4T.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.c4T.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.c4T.Location = new System.Drawing.Point(20, 20);
            this.c4T.Text = "Contratos vigentes";
            this.c4T.BackColor = System.Drawing.Color.Transparent;
            this.c4V.AutoSize = true;
            this.c4V.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
            this.c4V.ForeColor = System.Drawing.Color.White;
            this.c4V.Location = new System.Drawing.Point(15, 38);
            this.c4V.Text = "39";
            this.c4V.BackColor = System.Drawing.Color.Transparent;
            this.c4S.AutoSize = true;
            this.c4S.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.c4S.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.c4S.Location = new System.Drawing.Point(20, 80);
            this.c4S.Text = "Importe total activo $8.2M";
            this.c4S.BackColor = System.Drawing.Color.Transparent;
"""
expanded += """
            // pnlPromo1
            this.pnlPromo1.BorderRadius = 16;
            this.pnlPromo1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(26)))), ((int)(((byte)(43)))));
            this.pnlPromo1.Location = new System.Drawing.Point(30, 490);
            this.pnlPromo1.Size = new System.Drawing.Size(340, 200);
            this.pnlPromo1.Controls.Add(this.p1Badge);
            this.pnlPromo1.Controls.Add(this.p1Sub);
            this.pnlPromo1.Controls.Add(this.p1Title);
            this.pnlPromo1.Controls.Add(this.line1);
            this.pnlPromo1.Controls.Add(this.p1L1);
            this.pnlPromo1.Controls.Add(this.p1V1);
            this.pnlPromo1.Controls.Add(this.line2);
            this.pnlPromo1.Controls.Add(this.p1L2);
            this.pnlPromo1.Controls.Add(this.p1V2);
            this.pnlPromo1.Controls.Add(this.line3);
            this.pnlPromo1.Controls.Add(this.p1L3);
            this.pnlPromo1.Controls.Add(this.p1V3);
            this.p1Title.AutoSize = true;
            this.p1Title.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.p1Title.ForeColor = System.Drawing.Color.White;
            this.p1Title.Location = new System.Drawing.Point(20, 20);
            this.p1Title.Text = "Residencial Vista Norte";
            this.p1Title.BackColor = System.Drawing.Color.Transparent;
            this.p1Sub.AutoSize = true;
            this.p1Sub.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.p1Sub.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.p1Sub.Location = new System.Drawing.Point(20, 45);
            this.p1Sub.Text = "Tijuana, Baja California";
            this.p1Sub.BackColor = System.Drawing.Color.Transparent;
            this.p1Badge.BorderRadius = 10;
            this.p1Badge.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(50)))), ((int)(((byte)(40)))));
            this.p1Badge.Location = new System.Drawing.Point(260, 20);
            this.p1Badge.Size = new System.Drawing.Size(60, 24);
            this.p1Badge.Controls.Add(this.p1BadgeText);
            this.p1BadgeText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.p1BadgeText.Font = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.p1BadgeText.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(211)))), ((int)(((byte)(153)))));
            this.p1BadgeText.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.p1BadgeText.Text = "Activa";
            this.p1BadgeText.BackColor = System.Drawing.Color.Transparent;
            this.line1.Location = new System.Drawing.Point(20, 70);
            this.line1.Size = new System.Drawing.Size(300, 10);
            this.line1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(41)))), ((int)(((byte)(59)))));
            this.line1.BackColor = System.Drawing.Color.Transparent;
            this.p1L1.AutoSize = true;
            this.p1L1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.p1L1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.p1L1.Location = new System.Drawing.Point(20, 80);
            this.p1L1.Text = "Viviendas";
            this.p1L1.BackColor = System.Drawing.Color.Transparent;
            this.p1V1.AutoSize = false;
            this.p1V1.Location = new System.Drawing.Point(170, 80);
            this.p1V1.Size = new System.Drawing.Size(150, 20);
            this.p1V1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.p1V1.ForeColor = System.Drawing.Color.White;
            this.p1V1.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.p1V1.Text = "12 unidades";
            this.p1V1.BackColor = System.Drawing.Color.Transparent;
            this.line2.Location = new System.Drawing.Point(20, 110);
            this.line2.Size = new System.Drawing.Size(300, 10);
            this.line2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(41)))), ((int)(((byte)(59)))));
            this.line2.BackColor = System.Drawing.Color.Transparent;
            this.p1L2.AutoSize = true;
            this.p1L2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.p1L2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.p1L2.Location = new System.Drawing.Point(20, 120);
            this.p1L2.Text = "Tipo";
            this.p1L2.BackColor = System.Drawing.Color.Transparent;
            this.p1V2.AutoSize = false;
            this.p1V2.Location = new System.Drawing.Point(170, 120);
            this.p1V2.Size = new System.Drawing.Size(150, 20);
            this.p1V2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.p1V2.ForeColor = System.Drawing.Color.White;
            this.p1V2.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.p1V2.Text = "Residencial premium";
            this.p1V2.BackColor = System.Drawing.Color.Transparent;
            this.line3.Location = new System.Drawing.Point(20, 150);
            this.line3.Size = new System.Drawing.Size(300, 10);
            this.line3.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(41)))), ((int)(((byte)(59)))));
            this.line3.BackColor = System.Drawing.Color.Transparent;
            this.p1L3.AutoSize = true;
            this.p1L3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.p1L3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.p1L3.Location = new System.Drawing.Point(20, 160);
            this.p1L3.Text = "Empresas ligadas";
            this.p1L3.BackColor = System.Drawing.Color.Transparent;
            this.p1V3.AutoSize = false;
            this.p1V3.Location = new System.Drawing.Point(170, 160);
            this.p1V3.Size = new System.Drawing.Size(150, 20);
            this.p1V3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.p1V3.ForeColor = System.Drawing.Color.White;
            this.p1V3.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.p1V3.Text = "5 asociadas";
            this.p1V3.BackColor = System.Drawing.Color.Transparent;
"""
expanded += """
            // pnlPromo2
            this.pnlPromo2.BorderRadius = 16;
            this.pnlPromo2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(26)))), ((int)(((byte)(43)))));
            this.pnlPromo2.Location = new System.Drawing.Point(390, 490);
            this.pnlPromo2.Size = new System.Drawing.Size(340, 200);
            this.pnlPromo2.Controls.Add(this.p2Badge);
            this.pnlPromo2.Controls.Add(this.p2Sub);
            this.pnlPromo2.Controls.Add(this.p2Title);
            this.pnlPromo2.Controls.Add(this.line4);
            this.pnlPromo2.Controls.Add(this.p2L1);
            this.pnlPromo2.Controls.Add(this.p2V1);
            this.pnlPromo2.Controls.Add(this.line5);
            this.pnlPromo2.Controls.Add(this.p2L2);
            this.pnlPromo2.Controls.Add(this.p2V2);
            this.pnlPromo2.Controls.Add(this.line6);
            this.pnlPromo2.Controls.Add(this.p2L3);
            this.pnlPromo2.Controls.Add(this.p2V3);
            this.p2Title.AutoSize = true;
            this.p2Title.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.p2Title.ForeColor = System.Drawing.Color.White;
            this.p2Title.Location = new System.Drawing.Point(20, 20);
            this.p2Title.Text = "Jardines del Mar";
            this.p2Title.BackColor = System.Drawing.Color.Transparent;
            this.p2Sub.AutoSize = true;
            this.p2Sub.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.p2Sub.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.p2Sub.Location = new System.Drawing.Point(20, 45);
            this.p2Sub.Text = "Rosarito, B.C.";
            this.p2Sub.BackColor = System.Drawing.Color.Transparent;
            this.p2Badge.BorderRadius = 10;
            this.p2Badge.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(40)))), ((int)(((byte)(80)))));
            this.p2Badge.Location = new System.Drawing.Point(260, 20);
            this.p2Badge.Size = new System.Drawing.Size(60, 24);
            this.p2Badge.Controls.Add(this.p2BadgeText);
            this.p2BadgeText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.p2BadgeText.Font = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.p2BadgeText.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(160)))), ((int)(((byte)(250)))));
            this.p2BadgeText.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.p2BadgeText.Text = "En venta";
            this.p2BadgeText.BackColor = System.Drawing.Color.Transparent;
            this.line4.Location = new System.Drawing.Point(20, 70);
            this.line4.Size = new System.Drawing.Size(300, 10);
            this.line4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(41)))), ((int)(((byte)(59)))));
            this.line4.BackColor = System.Drawing.Color.Transparent;
            this.p2L1.AutoSize = true;
            this.p2L1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.p2L1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.p2L1.Location = new System.Drawing.Point(20, 80);
            this.p2L1.Text = "Viviendas";
            this.p2L1.BackColor = System.Drawing.Color.Transparent;
            this.p2V1.AutoSize = false;
            this.p2V1.Location = new System.Drawing.Point(170, 80);
            this.p2V1.Size = new System.Drawing.Size(150, 20);
            this.p2V1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.p2V1.ForeColor = System.Drawing.Color.White;
            this.p2V1.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.p2V1.Text = "8 unidades";
            this.p2V1.BackColor = System.Drawing.Color.Transparent;
            this.line5.Location = new System.Drawing.Point(20, 110);
            this.line5.Size = new System.Drawing.Size(300, 10);
            this.line5.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(41)))), ((int)(((byte)(59)))));
            this.line5.BackColor = System.Drawing.Color.Transparent;
            this.p2L2.AutoSize = true;
            this.p2L2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.p2L2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.p2L2.Location = new System.Drawing.Point(20, 120);
            this.p2L2.Text = "Plano situación";
            this.p2L2.BackColor = System.Drawing.Color.Transparent;
            this.p2V2.AutoSize = false;
            this.p2V2.Location = new System.Drawing.Point(170, 120);
            this.p2V2.Size = new System.Drawing.Size(150, 20);
            this.p2V2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.p2V2.ForeColor = System.Drawing.Color.White;
            this.p2V2.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.p2V2.Text = "Cargado";
            this.p2V2.BackColor = System.Drawing.Color.Transparent;
            this.line6.Location = new System.Drawing.Point(20, 150);
            this.line6.Size = new System.Drawing.Size(300, 10);
            this.line6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(41)))), ((int)(((byte)(59)))));
            this.line6.BackColor = System.Drawing.Color.Transparent;
            this.p2L3.AutoSize = true;
            this.p2L3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.p2L3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.p2L3.Location = new System.Drawing.Point(20, 160);
            this.p2L3.Text = "Ticket medio";
            this.p2L3.BackColor = System.Drawing.Color.Transparent;
            this.p2V3.AutoSize = false;
            this.p2V3.Location = new System.Drawing.Point(170, 160);
            this.p2V3.Size = new System.Drawing.Size(150, 20);
            this.p2V3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.p2V3.ForeColor = System.Drawing.Color.White;
            this.p2V3.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.p2V3.Text = "Alta demanda";
            this.p2V3.BackColor = System.Drawing.Color.Transparent;
"""
expanded += """
            // act1
            this.act1Icon.BorderRadius = 12;
            this.act1Icon.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(50)))), ((int)(((byte)(60)))));
            this.act1Icon.Location = new System.Drawing.Point(20, 25);
            this.act1Icon.Size = new System.Drawing.Size(40, 40);
            this.act1T.AutoSize = true;
            this.act1T.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.act1T.ForeColor = System.Drawing.Color.White;
            this.act1T.Location = new System.Drawing.Point(75, 20);
            this.act1T.Text = "Nueva vivienda registrada";
            this.act1T.BackColor = System.Drawing.Color.Transparent;
            this.act1S.AutoSize = true;
            this.act1S.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.act1S.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.act1S.Location = new System.Drawing.Point(75, 45);
            this.act1S.Text = "VIV-104 añadida a Residencial Vista Norte...";
            this.act1S.BackColor = System.Drawing.Color.Transparent;
            // act2
            this.act2Icon.BorderRadius = 12;
            this.act2Icon.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(60)))));
            this.act2Icon.Location = new System.Drawing.Point(20, 105);
            this.act2Icon.Size = new System.Drawing.Size(40, 40);
            this.act2T.AutoSize = true;
            this.act2T.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.act2T.ForeColor = System.Drawing.Color.White;
            this.act2T.Location = new System.Drawing.Point(75, 100);
            this.act2T.Text = "Contrato generado";
            this.act2T.BackColor = System.Drawing.Color.Transparent;
            this.act2S.AutoSize = true;
            this.act2S.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.act2S.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(163)))), ((int)(((byte)(184)))));
            this.act2S.Location = new System.Drawing.Point(75, 125);
            this.act2S.Text = "Constructora Delta firmó contrato por $850k...";
            this.act2S.BackColor = System.Drawing.Color.Transparent;
"""

import re
pattern = re.compile(r"            // Setup metric cards.*?\)\)\)\)\)\);", re.DOTALL)
content = pattern.sub(expanded, content)

pattern_funcs = re.compile(r"        private void SetupCard\(.*?\n    }\n}", re.DOTALL)
content = pattern_funcs.sub(r"    }\n}", content)

with open(r"C:\Users\Admin\source\repos\GestionPromocionesInmobiliarias\InmobilariaTopicos\InmobilariaTopicos\Form1.Designer.cs", "w", encoding="utf-8") as f:
    f.write(content)
print("D")
